# https://github.com/marketplace/actions/go-release-binaries
on:
  push:
    branches:
      - main
    tags:        
      - '*'
  release:
    types: [created]

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        #goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v3
    - name: install packages
      run: |
          sudo go install github.com/fyne-io/fyne-cross@latest
          fyne-cross linux -output carbon-app .
          #sudo apt update
          #sudo apt-get -y install bc gcc libgl1-mesa-dev libwayland-dev libx11-dev libxkbcommon-dev xorg-dev xvfb
          #sudo apt-get -y install libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev gcc pkg-config libxxf86vm-dev
    #- uses: wangyoucao577/go-release-action@v1.51
    #  with:
    #    github_token: ${{ secrets.GITHUB_TOKEN }}
    #    goos: ${{ matrix.goos }}
    #    goarch: ${{ matrix.goarch }}
    #    binary_name: carbon-app
    #    retry: 10
    #    sha256sum: true
    #    pre_command: go mod tidy
