# https://github.com/marketplace/actions/go-release-binaries
name: Build carbonapp
on:
  push:
    branches:
      - main
    tags:        
      - '*'
  release:
    types: [created]

jobs:
  fyne-cross-and-release:
    name: release linux/amd64
    runs-on: ubuntu-latest
    #strategy:
    #  matrix:
    #    goos: [linux]
    #    #goos: [linux, windows, darwin]
    #    goarch: [amd64]
    #    #goarch: [amd64, arm64]
    #    exclude:
    #      - goarch: arm64
    #        goos: windows
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v3
    - name: install packages
      run: |
          go version
          sudo apt update
          sudo apt-get -y install bc gcc libgl1-mesa-dev libwayland-dev libx11-dev libxkbcommon-dev xorg-dev xvfb
          go install github.com/fyne-io/fyne-cross@latest
          go install github.com/tcnksm/ghr@latest
          export PATH=$PATH:~/go/bin
          #echo "$HOME/go/bin" >> $GITHUB_PATH
    - name: compile
      run: |
          fyne-cross linux -output carbon-app -arch=amd64,arm64 -debug .
          mv fyne-cross/dist/linux-arm64/carbonapp-arm64.tar.xz
          mv fyne-cross/dist/linux-amd64/carbonapp-amd64.tar.xz
          #sudo apt update
          #sudo apt-get -y install bc gcc libgl1-mesa-dev libwayland-dev libx11-dev libxkbcommon-dev xorg-dev xvfb
          #sudo apt-get -y install libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev gcc pkg-config libxxf86vm-dev
    #- name: Upload artifacts for linux-amd64
    #  uses: actions/upload-artifact@v4
    #  with:
    #    name: carbonapp-amd64
    #    path: fyne-cross/dist/linux-amd64/
    #- name: Upload artifacts for linux-arm64
    #  uses: actions/upload-artifact@v4
    #  with:
    #    name: carbonapp-arm64
    #    path: fyne-cross/dist/linux-arm64/
    - name: Release dist linux-amd64
      uses: fnkr/github-action-ghr@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GHR_PATH: fyne-cross/dist/carbonapp-amd64.tar.xz
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        GHR_REPLACE: true
    - name: Release dist linux-arm64
      uses: fnkr/github-action-ghr@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GHR_PATH: fyne-cross/dist/carbonapp-arm64.tar.xz
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        GHR_REPLACE: true
    #- name: Release linux-arm64
    #  uses: fnkr/github-action-ghr@v1
    #  if: startsWith(github.ref, 'refs/tags/')
    #  env:
    #    GHR_PATH: fyne-cross/dist/linux-arm64/
    #    GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
    #    GHR_REPLACE: true
    #- uses: wangyoucao577/go-release-action@v1.51
    #  with:
    #    github_token: ${{ secrets.GITHUB_TOKEN }}
    #    goos: ${{ matrix.goos }}
    #    goarch: ${{ matrix.goarch }}
    #    binary_name: carbon-app
    #    retry: 10
    #    sha256sum: true
    #    pre_command: go mod tidy
